export const legacyHomeCopy = {
  en: {
    demoLabel: "INTERACTIVE DEMO",
    hero: {
      eyebrow: "OPEN-SOURCE VIDEO OBSERVATORY",
      title: "See what your video hides.",
      description: "Find the exact intervals that need review, inspect frame evidence, and understand each detector’s limitations.",
      analyze: "Analyze a video",
      demo: "View interactive demo",
      github: "View on GitHub",
      local: "Local-first · Browser CPU · No default upload",
      intervals: "review intervals",
      mediaLabel: "Procedural optical aperture observatory scene",
    },
    proof: {
      eyebrow: "FRAME-LEVEL PRODUCT PROOF",
      title: "One timeline. Every observable interval.",
      description: "Select an interval to synchronize the playhead, overlay, evidence, and detector detail.",
      mediaLabel: "Procedural night observation grid",
      currentTime: "Active time",
    },
    narrative: {
      eyebrow: "DIAGNOSIS, NOT GUESSWORK",
      title: "Follow the signal to the frame.",
      description: "The player stays in view while each observation reveals its interval, evidence, and limitations. Scrolling remains yours.",
      mediaLabel: "Procedural diagnostic mesh",
      browserCpu: "BROWSER CPU",
      optional: "OPTIONAL · DEMO",
    },
    metrics: {
      eyebrow: "TEMPORAL SIGNAL SPECTRUM",
      title: "Detector-local values, never a universal score.",
      description: "Each signal keeps its own meaning, time context, and limitation.",
      cpu: "Browser CPU signals",
      optional: "Optional demonstration signals",
      evidence: "Editorial evidence atlas",
      evidenceLabels: {
        a: "Procedural cyan caustic evidence study",
        b: "Procedural violet lattice evidence study",
        c: "Procedural amber contour evidence study",
      },
    },
    compare: {
      eyebrow: "SYNCHRONIZED COMPARISON",
      title: "Compare observations, detector by detector.",
      description: "Aligned playback reveals where each video carries fewer, equal, or unknown observable events—without declaring a universal winner.",
      a: "Comparison A · procedural cool topography",
      b: "Comparison B · procedural dawn spectrum",
      sync: "Synchronized preview position",
      play: "Play both previews",
      pause: "Pause both previews",
      open: "Open comparison workspace",
    },
    workflow: {
      eyebrow: "FROM CLIP TO EVIDENCE",
      title: "Upload → Analyze → Inspect → Improve",
      steps: [
        { title: "Upload", description: "Choose a local video or consent to a direct URL request." },
        { title: "Analyze", description: "Sample frames once and run four browser CPU heuristics." },
        { title: "Inspect", description: "Jump from each interval to its evidence and limitations." },
        { title: "Improve", description: "Use observations to guide the next human review or generation." },
      ],
    },
    openSource: {
      eyebrow: "OPEN PROTOCOL",
      title: "Build detectors without rewriting the observatory.",
      description: "Stable Finding fields, detector-local parameters, reproducible ordering, and JSON reports keep the framework inspectable.",
      protocol: "Detector protocol",
      benchmark: "Benchmark reports each detector independently. Synthetic fixtures are engineering regression data, not real-video accuracy.",
      copy: "Copy JSON example",
      copied: "Copied",
      copyFailed: "Copy failed",
    },
    final: {
      eyebrow: "READY FOR LOCAL REVIEW",
      title: "Your video is ready to be understood.",
      description: "Start in the browser, inspect the demo, or study the open-source implementation.",
      analyze: "Analyze a video",
      demo: "Try interactive demo",
      github: "View on GitHub",
    },
  },
  "zh-CN": {
    demoLabel: "交互演示 · INTERACTIVE DEMO",
    hero: {
      eyebrow: "开源视频观测站",
      title: "看见视频隐藏的细节。",
      description: "定位需要复核的准确时间区间，检查逐帧证据，并理解每个检测器的局限。",
      analyze: "分析视频",
      demo: "查看交互演示",
      github: "在 GitHub 查看",
      local: "本地优先 · 浏览器 CPU · 默认不上传",
      intervals: "个复核区间",
      mediaLabel: "程序化光学孔径观测场景",
    },
    proof: {
      eyebrow: "逐帧产品实证",
      title: "一条时间轴，看清每个可观察区间。",
      description: "选择一个区间，播放头、检测框、证据和检测器详情会同步定位。",
      mediaLabel: "程序化夜间观测网格",
      currentTime: "当前时间",
    },
    narrative: {
      eyebrow: "用证据诊断，而非猜测",
      title: "沿着信号找到具体帧。",
      description: "播放器保持可见，每个观察结果依次展示区间、证据和局限；页面不会劫持滚动。",
      mediaLabel: "程序化诊断网格",
      browserCpu: "浏览器 CPU",
      optional: "可选 · 演示",
    },
    metrics: {
      eyebrow: "时间信号频谱",
      title: "检测器内数值，而非通用总分。",
      description: "每项信号都保留自身含义、时间上下文和局限。",
      cpu: "浏览器 CPU 信号",
      optional: "可选演示信号",
      evidence: "编辑式证据图谱",
      evidenceLabels: {
        a: "程序化青色焦散证据图",
        b: "程序化紫色晶格证据图",
        c: "程序化琥珀等高线证据图",
      },
    },
    compare: {
      eyebrow: "同步对比",
      title: "逐个检测器对比观察结果。",
      description: "同步播放展示每段视频在哪些检测器上事件更少、相同或未知，但不会武断地给出全局胜负。",
      a: "对比 A · 程序化冷色地形",
      b: "对比 B · 程序化黎明光谱",
      sync: "同步预览位置",
      play: "同步播放两个预览",
      pause: "暂停两个预览",
      open: "打开对比工作区",
    },
    workflow: {
      eyebrow: "从视频到证据",
      title: "上传 → 分析 → 检查 → 改进",
      steps: [
        { title: "上传", description: "选择本地视频，或确认隐私提示后请求视频直链。" },
        { title: "分析", description: "只抽取一次帧，并运行四个浏览器 CPU 启发式检测器。" },
        { title: "检查", description: "从每个时间区间跳转到对应证据和局限说明。" },
        { title: "改进", description: "用观察结果指导下一轮人工复核或视频生成。" },
      ],
    },
    openSource: {
      eyebrow: "开放协议",
      title: "新增检测器，无需重写观测站。",
      description: "稳定的 Finding 字段、检测器内参数、确定性排序和 JSON 报告让框架始终可检查。",
      protocol: "检测器协议",
      benchmark: "Benchmark 分别报告每个检测器。合成样例只是工程回归数据，并不代表真实视频准确率。",
      copy: "复制 JSON 示例",
      copied: "已复制",
      copyFailed: "复制失败",
    },
    final: {
      eyebrow: "开始本地复核",
      title: "你的视频，已经准备好被理解。",
      description: "在浏览器中开始分析、体验交互演示，或查看开源实现。",
      analyze: "分析视频",
      demo: "体验交互演示",
      github: "在 GitHub 查看",
    },
  },
} as const;
