"""Reviewable local Advanced AI contracts and services."""

from videoscope.intelligence.bridge import (
    reviewed_content_ranges,
    reviewed_text_suggestions,
)
from videoscope.intelligence.evaluation import (
    GroundingMetrics,
    evaluate_grounded_ranges,
    temporal_iou,
)
from videoscope.intelligence.fake import (
    FakeASRProvider,
    FakeContentIntelligenceProvider,
)
from videoscope.intelligence.models import (
    INTELLIGENCE_SCHEMA_VERSION,
    AIExecutionRecord,
    AIExecutionStatus,
    AIRange,
    AIReviewDecision,
    AIReviewManifest,
    AISourceEvidence,
    AISuggestion,
    AISuggestionBatch,
    AISuggestionDraft,
    AITranscript,
    AITranscriptSegment,
    AITranscriptSegmentDraft,
    ContentIntelligenceRequest,
    ReviewDecisionKind,
    SuggestionKind,
    canonical_json,
    make_ai_transcript_hash,
    make_ai_transcript_segment_id,
    make_batch_digest,
    make_review_digest,
    make_suggestion_id,
    suggestion_sort_key,
)
from videoscope.intelligence.pipeline import (
    AdvancedAICancelledError,
    AdvancedAIConfig,
    AdvancedAIContentPipeline,
    AdvancedAIDependencies,
    AdvancedAIPreparation,
    AdvancedAIReview,
)
from videoscope.intelligence.protocols import ASRProvider, ContentIntelligenceProvider
from videoscope.intelligence.runtime import (
    get_asr_provider,
    get_content_intelligence_provider,
    register_faster_whisper_provider,
    register_ollama_provider,
)
from videoscope.intelligence.serialization import (
    read_ai_transcript,
    read_review_manifest,
    read_suggestion_batch,
    write_intelligence_json,
)
from videoscope.intelligence.service import (
    IntelligenceError,
    IntelligenceGroundingError,
    accepted_suggestions,
    build_intelligence_request,
    build_review_manifest,
    normalize_asr_transcript,
    normalize_trusted_transcript,
    run_content_intelligence,
)

__all__ = [
    "ASRProvider",
    "AdvancedAIConfig",
    "AdvancedAICancelledError",
    "AdvancedAIContentPipeline",
    "AdvancedAIDependencies",
    "AdvancedAIPreparation",
    "AdvancedAIReview",
    "INTELLIGENCE_SCHEMA_VERSION",
    "AIExecutionRecord",
    "AIExecutionStatus",
    "AIRange",
    "AIReviewDecision",
    "AIReviewManifest",
    "AISourceEvidence",
    "AISuggestion",
    "AISuggestionBatch",
    "AISuggestionDraft",
    "AITranscript",
    "AITranscriptSegment",
    "AITranscriptSegmentDraft",
    "ContentIntelligenceProvider",
    "ContentIntelligenceRequest",
    "FakeASRProvider",
    "FakeContentIntelligenceProvider",
    "GroundingMetrics",
    "IntelligenceError",
    "IntelligenceGroundingError",
    "ReviewDecisionKind",
    "SuggestionKind",
    "accepted_suggestions",
    "build_intelligence_request",
    "build_review_manifest",
    "canonical_json",
    "make_ai_transcript_hash",
    "make_ai_transcript_segment_id",
    "make_batch_digest",
    "make_review_digest",
    "make_suggestion_id",
    "get_asr_provider",
    "get_content_intelligence_provider",
    "evaluate_grounded_ranges",
    "normalize_asr_transcript",
    "normalize_trusted_transcript",
    "read_ai_transcript",
    "read_review_manifest",
    "read_suggestion_batch",
    "register_faster_whisper_provider",
    "register_ollama_provider",
    "reviewed_content_ranges",
    "reviewed_text_suggestions",
    "run_content_intelligence",
    "suggestion_sort_key",
    "temporal_iou",
    "write_intelligence_json",
]
