"""Optional provider boundaries for local content intelligence."""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path
from typing import Protocol, runtime_checkable

from videoscope.ai.models import Device, ModelHealth, Precision
from videoscope.intelligence.models import (
    AISuggestionDraft,
    AITranscriptSegmentDraft,
    ContentIntelligenceRequest,
)


@runtime_checkable
class ASRProvider(Protocol):
    @property
    def provider_id(self) -> str: ...
    @property
    def model_id(self) -> str: ...
    @property
    def device(self) -> Device: ...
    @property
    def precision(self) -> Precision: ...
    def load(self) -> None: ...
    def unload(self) -> None: ...
    def health(self) -> ModelHealth: ...
    def transcribe(self, media_path: Path) -> Sequence[AITranscriptSegmentDraft]: ...


@runtime_checkable
class ContentIntelligenceProvider(Protocol):
    @property
    def provider_id(self) -> str: ...
    @property
    def model_id(self) -> str: ...
    @property
    def device(self) -> Device: ...
    @property
    def precision(self) -> Precision: ...
    def load(self) -> None: ...
    def unload(self) -> None: ...
    def health(self) -> ModelHealth: ...
    def suggest(
        self, request: ContentIntelligenceRequest
    ) -> Sequence[AISuggestionDraft]: ...


__all__ = ["ASRProvider", "ContentIntelligenceProvider"]
